//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noterium.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Noterium.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter master password:.
        /// </summary>
        public static string Authentication_EnterMasterPassword {
            get {
                return ResourceManager.GetString("Authentication_EnterMasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string Authentication_PasswordBoxWatermark {
            get {
                return ResourceManager.GetString("Authentication_PasswordBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string BackupManager_Restore {
            get {
                return ResourceManager.GetString("BackupManager_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select backup set:.
        /// </summary>
        public static string BackupManager_SelectSet {
            get {
                return ResourceManager.GetString("BackupManager_SelectSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument PagePadding=&quot;0,0,0,0&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;&lt;FlowDocument.Style&gt;&lt;Style TargetType=&quot;FlowDocument&quot;&gt;&lt;Style.Resources&gt;&lt;ResourceDictionary /&gt;&lt;/Style.Resources&gt;&lt;Setter Property=&quot;TextElement.FontFamily&quot;&gt;&lt;Setter.Value&gt;&lt;FontFamily&gt;Segoe UI&lt;/FontFamily&gt;&lt;/Setter.Value&gt;&lt;/Setter&gt;&lt;Setter Property=&quot;Block.TextAlignment&quot;&gt;&lt;Setter.Value&gt;&lt;x:Static Member=&quot;TextAlignment.Left&quot; /&gt;&lt;/Setter.Value&gt;&lt;/Setter&gt;&lt;Setter Propert [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Help_Document {
            get {
                return ResourceManager.GetString("Help_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librarys.
        /// </summary>
        public static string JumpList_LibrarysCategoryName {
            get {
                return ResourceManager.GetString("JumpList_LibrarysCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads the library named .
        /// </summary>
        public static string JumpList_LoadLibraryTitle {
            get {
                return ResourceManager.GetString("JumpList_LoadLibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add library.
        /// </summary>
        public static string Librarys_AddLibrary {
            get {
                return ResourceManager.GetString("Librarys_AddLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select defalut library:.
        /// </summary>
        public static string Librarys_DefaultLibrary {
            get {
                return ResourceManager.GetString("Librarys_DefaultLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Librarys_Delete {
            get {
                return ResourceManager.GetString("Librarys_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librarys.
        /// </summary>
        public static string Librarys_FlyoutTitle {
            get {
                return ResourceManager.GetString("Librarys_FlyoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Librarys_Load {
            get {
                return ResourceManager.GetString("Librarys_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading library.
        /// </summary>
        public static string Loading_Loading {
            get {
                return ResourceManager.GetString("Loading_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;log4net&gt;
        ///    &lt;root&gt;
        ///      &lt;level value=&quot;DEBUG&quot;/&gt;
        ///      &lt;appender-ref ref=&quot;LogFileAppender&quot;/&gt;
        ///      &lt;appender-ref ref=&quot;ColoredConsoleAppender&quot;/&gt;
        ///    &lt;/root&gt;
        ///    &lt;appender name=&quot;LogFileAppender&quot; type=&quot;log4net.Appender.RollingFileAppender&quot;&gt;
        ///      &lt;param name=&quot;File&quot; value=&quot;{LOGPATH}\noterium.log&quot;/&gt;
        ///      &lt;param name=&quot;AppendToFile&quot; value=&quot;true&quot;/&gt;
        ///      &lt;rollingStyle value=&quot;Composite&quot; /&gt;
        ///      &lt;datePattern value=&quot;.yyyyMMdd&quot; /&gt;
        ///      &lt;maxSizeRollBackups value=&quot;10&quot;/&gt;
        ///      &lt;maximumFileSize value=&quot;1MB&quot;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LogXml {
            get {
                return ResourceManager.GetString("LogXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note.
        /// </summary>
        public static string Main_AddNote {
            get {
                return ResourceManager.GetString("Main_AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add notebook.
        /// </summary>
        public static string Main_AddNotebook {
            get {
                return ResourceManager.GetString("Main_AddNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add secure note.
        /// </summary>
        public static string Main_AddSecureNote {
            get {
                return ResourceManager.GetString("Main_AddSecureNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All notes.
        /// </summary>
        public static string Main_AllNotes {
            get {
                return ResourceManager.GetString("Main_AllNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        public static string Main_Favourites {
            get {
                return ResourceManager.GetString("Main_Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Main_Library {
            get {
                return ResourceManager.GetString("Main_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librarys.
        /// </summary>
        public static string Main_Librarys {
            get {
                return ResourceManager.GetString("Main_Librarys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a note to view and edit it..
        /// </summary>
        public static string Main_NoNotesMessage {
            get {
                return ResourceManager.GetString("Main_NoNotesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebooks.
        /// </summary>
        public static string Main_Notebooks {
            get {
                return ResourceManager.GetString("Main_Notebooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string Main_Recent {
            get {
                return ResourceManager.GetString("Main_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Main_Tags {
            get {
                return ResourceManager.GetString("Main_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string Main_Trash {
            get {
                return ResourceManager.GetString("Main_Trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy note.
        /// </summary>
        public static string Note_Copy {
            get {
                return ResourceManager.GetString("Note_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are aboute to copy a secure note, this will decrypt the note contents and store it in plain text in clipboard. Continue?.
        /// </summary>
        public static string Note_Copy_SecureText {
            get {
                return ResourceManager.GetString("Note_Copy_SecureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying secure note.
        /// </summary>
        public static string Note_Copy_SecureTitle {
            get {
                return ResourceManager.GetString("Note_Copy_SecureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste note.
        /// </summary>
        public static string Note_Paste {
            get {
                return ResourceManager.GetString("Note_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files (drag and drop files below):.
        /// </summary>
        public static string NoteEditor_FilesAreaLabel {
            get {
                return ResourceManager.GetString("NoteEditor_FilesAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add tags....
        /// </summary>
        public static string NoteEditor_Tags_Watermark {
            get {
                return ResourceManager.GetString("NoteEditor_Tags_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format text as code.
        /// </summary>
        public static string NoteEditor_Toolbar_Code {
            get {
                return ResourceManager.GetString("NoteEditor_Toolbar_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert comment.
        /// </summary>
        public static string NoteEditor_Toolbar_Comment {
            get {
                return ResourceManager.GetString("NoteEditor_Toolbar_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert image tag.
        /// </summary>
        public static string NoteEditor_Toolbar_Image {
            get {
                return ResourceManager.GetString("NoteEditor_Toolbar_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle word wrap.
        /// </summary>
        public static string NoteEditor_Toolbar_ToggleWordWrap {
            get {
                return ResourceManager.GetString("NoteEditor_Toolbar_ToggleWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        public static string Notes_Encrypted {
            get {
                return ResourceManager.GetString("Notes_Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite.
        /// </summary>
        public static string Notes_Favourite {
            get {
                return ResourceManager.GetString("Notes_Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect from deletion.
        /// </summary>
        public static string Notes_ProtectFromDelete {
            get {
                return ResourceManager.GetString("Notes_ProtectFromDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a note.
        /// </summary>
        public static string Search_FindANote {
            get {
                return ResourceManager.GetString("Search_FindANote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Search_SearchBoxWatermark {
            get {
                return ResourceManager.GetString("Search_SearchBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Noterium.
        /// </summary>
        public static string Settings_AboutNoterium {
            get {
                return ResourceManager.GetString("Settings_AboutNoterium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically backup.
        /// </summary>
        public static string Settings_AutomaticallyBackup {
            get {
                return ResourceManager.GetString("Settings_AutomaticallyBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup now.
        /// </summary>
        public static string Settings_BackupNow {
            get {
                return ResourceManager.GetString("Settings_BackupNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups.
        /// </summary>
        public static string Settings_Backups {
            get {
                return ResourceManager.GetString("Settings_Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of backup to keep.
        /// </summary>
        public static string Settings_BackupsToKeep {
            get {
                return ResourceManager.GetString("Settings_BackupsToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        public static string Settings_Behaviour {
            get {
                return ResourceManager.GetString("Settings_Behaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        public static string Settings_CapsLockWarning1 {
            get {
                return ResourceManager.GetString("Settings_CapsLockWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPS LOCK.
        /// </summary>
        public static string Settings_CapsLockWarning2 {
            get {
                return ResourceManager.GetString("Settings_CapsLockWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on. This can result in you entering another password than you excpect..
        /// </summary>
        public static string Settings_CapsLockWarning3 {
            get {
                return ResourceManager.GetString("Settings_CapsLockWarning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default view for notes:.
        /// </summary>
        public static string Settings_DefaultNoteView {
            get {
                return ResourceManager.GetString("Settings_DefaultNoteView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable secure notes.
        /// </summary>
        public static string Settings_DisableSecureNotes {
            get {
                return ResourceManager.GetString("Settings_DisableSecureNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable experimental features.
        /// </summary>
        public static string Settings_EnableExperimentalFeatures {
            get {
                return ResourceManager.GetString("Settings_EnableExperimentalFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable secure notes.
        /// </summary>
        public static string Settings_EnableSecureNotes {
            get {
                return ResourceManager.GetString("Settings_EnableSecureNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption password.
        /// </summary>
        public static string Settings_EncryptionPassword {
            get {
                return ResourceManager.GetString("Settings_EncryptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_FlyoutTitle {
            get {
                return ResourceManager.GetString("Settings_FlyoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last backup occured on:.
        /// </summary>
        public static string Settings_LastBackup {
            get {
                return ResourceManager.GetString("Settings_LastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock main window after (minutes):.
        /// </summary>
        public static string Settings_LockMainWindowAfterMinutes {
            get {
                return ResourceManager.GetString("Settings_LockMainWindowAfterMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open backup manager.
        /// </summary>
        public static string Settings_OpenBackupManager {
            get {
                return ResourceManager.GetString("Settings_OpenBackupManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string Settings_RepeatEncryptionPassword {
            get {
                return ResourceManager.GetString("Settings_RepeatEncryptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Settings_Security {
            get {
                return ResourceManager.GetString("Settings_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        public static string Settings_Visual {
            get {
                return ResourceManager.GetString("Settings_Visual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Time_Day {
            get {
                return ResourceManager.GetString("Time_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Time_Days {
            get {
                return ResourceManager.GetString("Time_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string Time_Min {
            get {
                return ResourceManager.GetString("Time_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM, yyyy.
        /// </summary>
        public static string Time_NoteCreatedDateFormat {
            get {
                return ResourceManager.GetString("Time_NoteCreatedDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMM.
        /// </summary>
        public static string Time_NoteCreatedDateFormatSameYear {
            get {
                return ResourceManager.GetString("Time_NoteCreatedDateFormatSameYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string Time_Now {
            get {
                return ResourceManager.GetString("Time_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noterium.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
